name: Build
on:
  push:
  pull_request:

jobs:
  # https://github.com/pre-commit/action
  pre-commit:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - uses: pre-commit/action@v3.0.1

  build:
    name: Build docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip
          cache-dependency-path: "**/requirements.txt"

      - name: Install dependencies
        run: python -m pip install -r docs/requirements.txt

      - name: Build docs
        run: |
          cd docs
          make html

      - name: Link check
        run: |
          cd docs
          make SPHINXOPTS="--color --keep-going" linkcheck
